---
title: "R & RStudio"
---

## R

R is a programming language designed to facilitate statistical analyses and to generate graphs. R is also the program that converts what we write into something your computer can execute.

## RStudio

RStudio is an IDE -- Integrated Development Environment. It provides a visual interface to work with R the language and R the program. It consists of several key elements.

1. a scripting pane, where we write stuff
2. an R console, where R runs and processes what you right
3. an environment pane, where we can see the data objects, functions etc that we create
4. a viewing pane that gives us access to our files, plots, and help

<div class = "note">
Most people who work with R do it using RStudio. But this is not necessary. All you need is a plain text editor and an R console that will compile what you write.
</div>

## Building Blocks

The big difference with working in something like R, over say Excel or another point and click tool for working with data, is that it moves us into the realm of programming, which brings with it a need to understand some core concepts about how data are handled and stored by computers.

While we're not outright programming, we will be writing scripts to do things with our data --and basically, that's what a program is -- data, and a series of instructions--functions--to do things with these data.

## How it Works

1. You write instructions
2. You give those instructions some data
3. A compiler converts those instructions to something you computer can execute
4. Your computer executes those instructions on your data
5. You get the results presented to you, either on your screen, stored to a file, sent to a printer etc.